# 구글드라이브 연결

파일 > 드라이브 마운트 클릭

In [ ]:
import os
from pathlib import Path
DATA_DIR = Path("drive/MyDrive/kw/추천특강/강의자료/data/")
os.listdir(DATA_DIR)

# 데이터 로드

https://grouplens.org/datasets/movielens/

https://files.grouplens.org/datasets/movielens/ml-10m-README.html

In [ ]:
MOVIE_DATA_PATH = f"{DATA_DIR}/movies.csv"
RATING_DATA_PATH = f"{DATA_DIR}/ratings.csv"
TAG_DATA_PATH = f"{DATA_DIR}/tags.csv"

In [ ]:
import pandas as pd

movies_df = pd.read_csv(MOVIE_DATA_PATH)
ratings_df = pd.read_csv(RATING_DATA_PATH)
tags_df = pd.read_csv(TAG_DATA_PATH)

In [ ]:
movies_df

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [ ]:
ratings_df

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [ ]:
tags_df

      userId  movieId               tag   timestamp
0          2    60756             funny  1445714994
1          2    60756   Highly quotable  1445714996
2          2    60756      will ferrell  1445714992
3          2    89774      Boxing story  1445715207
4          2    89774               MMA  1445715200
...      ...      ...               ...         ...
3678     606     7382         for katie  1171234019
3679     606     7936           austere  1173392334
3680     610     3265            gun fu  1493843984
3681     610     3265  heroic bloodshed  1493843978
3682     610   168248  Heroic Bloodshed  1493844270

[3683 rows x 4 columns]

# 전처리

## 컬럼명 변경

In [ ]:
# movies_df = movies_df.rename(columns={'movieId': 'movie_id'}, inplace=True)
movies_df = movies_df.rename(columns={'movieId': 'movie_id'})
ratings_df = ratings_df.rename(columns={'movieId': 'movie_id', 'userId': 'user_id'})
tags_df = tags_df.rename(columns={'movieId': 'movie_id', 'userId': 'user_id'})

In [ ]:
movies_df

,movie_id,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [ ]:
ratings_df

        user_id  movie_id  rating   timestamp
0             1         1     4.0   964982703
1             1         3     4.0   964981247
2             1         6     4.0   964982224
3             1        47     5.0   964983815
4             1        50     5.0   964982931
...         ...       ...     ...         ...
100831      610    166534     4.0  1493848402
100832      610    168248     5.0  1493850091
100833      610    168250     5.0  1494273047
100834      610    168252     5.0  1493846352
100835      610    170875     3.0  1493846415

[100836 rows x 4 columns]

In [ ]:
tags_df

      user_id  movie_id               tag   timestamp
0           2     60756             funny  1445714994
1           2     60756   Highly quotable  1445714996
2           2     60756      will ferrell  1445714992
3           2     89774      Boxing story  1445715207
4           2     89774               MMA  1445715200
...       ...       ...               ...         ...
3678      606      7382         for katie  1171234019
3679      606      7936           austere  1173392334
3680      610      3265            gun fu  1493843984
3681      610      3265  heroic bloodshed  1493843978
3682      610    168248  Heroic Bloodshed  1493844270

[3683 rows x 4 columns]

## ID 형변환

In [ ]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  9742 non-null   int64
 1   title     9742 non-null   object
 2   genres    9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

In [ ]:
movies_df['movie_id'] = movies_df['movie_id'].astype(str)
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  9742 non-null   object
 1   title     9742 non-null   object
 2   genres    9742 non-null   object
dtypes: object(3)
memory usage: 228.5+ KB

In [ ]:
ratings_df['user_id'] = ratings_df['user_id'].astype(str)
ratings_df['movie_id'] = ratings_df['movie_id'].astype(str)
ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   user_id    100836 non-null  object
 1   movie_id   100836 non-null  object
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(1), object(2)
memory usage: 3.1+ MB

In [ ]:
tags_df['user_id'] = tags_df['user_id'].astype(str)
tags_df['movie_id'] = tags_df['movie_id'].astype(str)
tags_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3683 entries, 0 to 3682
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   user_id    3683 non-null   object
 1   movie_id   3683 non-null   object
 2   tag        3683 non-null   object
 3   timestamp  3683 non-null   int64
dtypes: int64(1), object(3)
memory usage: 115.2+ KB

## 중복 처리

### 중복체크

In [ ]:
len(movies_df)  # 무비 데이터 수

9742

In [ ]:
movies_df['movie_id'].nunique()  # 무비 id 수

9742

In [ ]:
movies_df['title'].nunique()  # 무비 제목 != 무비 id 수

9737

In [ ]:
# 제목 중복된 영화
movies_df[movies_df.duplicated('title')]

,movie_id,title,genres
5601,26958,Emma (1996),Romance
6932,64997,War of the Worlds (2005),Action|Sci-Fi
9106,144606,Confessions of a Dangerous Mind (2002),Comedy|Crime|Drama|Romance|Thriller
9135,147002,Eros (2004),Drama|Romance
9468,168358,Saturn 3 (1980),Sci-Fi|Thriller

In [ ]:
# 중복 개수까지 체크
movies_df['title'].value_counts()[movies_df['title'].value_counts() > 1]

title
Emma (1996)                               2
War of the Worlds (2005)                  2
Eros (2004)                               2
Confessions of a Dangerous Mind (2002)    2
Saturn 3 (1980)                           2
Name: count, dtype: int64

### 중복값 처리

영화1) Emma

movies 데이터 처리

In [ ]:
movie_titile = "Emma (1996)"
movies_df[movies_df['title'] == movie_titile]

     movie_id        title                genres
650       838  Emma (1996)  Comedy|Drama|Romance
5601    26958  Emma (1996)               Romance

In [ ]:
unique_id = movies_df[movies_df['title'] == movie_titile]['movie_id'].values[0]
unique_id

'838'

In [ ]:
duplicated_id = movies_df[movies_df['title'] == movie_titile]['movie_id'].values[1]
duplicated_id

'26958'

In [ ]:
# 중복 데이터 제거
movies_df = movies_df[~(movies_df['movie_id'] == duplicated_id)].copy()
movies_df

,movie_id,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

ratings 데이터 처리

In [ ]:
ratings_df[ratings_df['movie_id'] == duplicated_id]

      user_id movie_id  rating   timestamp
80596     509    26958     3.5  1436031753

In [ ]:
duplicated_index = ratings_df[ratings_df['movie_id'] == duplicated_id].index
duplicated_index

Index([80596], dtype='int64')

In [ ]:
ratings_df.loc[duplicated_index, 'movie_id'] = unique_id

In [ ]:
# 검산: 삭제 여부 확인
ratings_df[ratings_df['movie_id'] == duplicated_id]

Empty DataFrame
Columns: [user_id, movie_id, rating, timestamp]
Index: []

In [ ]:
# 검산: 중복 id 변경 확인
ratings_df.loc[duplicated_index]

      user_id movie_id  rating   timestamp
80596     509      838     3.5  1436031753

영화2) War of the Worlds

movies 데이터 처리

In [ ]:
movie_titile = "War of the Worlds (2005)"
movies_df[movies_df['title'] == movie_titile]

     movie_id                     title                            genres
5931    34048  War of the Worlds (2005)  Action|Adventure|Sci-Fi|Thriller
6932    64997  War of the Worlds (2005)                     Action|Sci-Fi

In [ ]:
unique_id = movies_df[movies_df['title'] == movie_titile]['movie_id'].values[0]
unique_id

'34048'

In [ ]:
duplicated_id = movies_df[movies_df['title'] == movie_titile]['movie_id'].values[1]
duplicated_id

'64997'

In [ ]:
# 중복 데이터 제거
movies_df = movies_df[~(movies_df['movie_id'] == duplicated_id)].copy()
movies_df

,movie_id,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

ratings 데이터 처리

In [ ]:
ratings_df[ratings_df['movie_id'] == duplicated_id]

      user_id movie_id  rating   timestamp
4747       28    64997     3.5  1234850075
11451      68    64997     2.5  1230497715

In [ ]:
duplicated_index = ratings_df[ratings_df['movie_id'] == duplicated_id].index
duplicated_index

Index([4747, 11451], dtype='int64')

In [ ]:
ratings_df.loc[duplicated_index, 'movie_id'] = unique_id

In [ ]:
# 검산: 삭제 여부 확인
ratings_df[ratings_df['movie_id'] == duplicated_id]

Empty DataFrame
Columns: [user_id, movie_id, rating, timestamp]
Index: []

In [ ]:
# 검산: 중복 id 변경 확인
ratings_df.loc[duplicated_index]

      user_id movie_id  rating   timestamp
4747       28    34048     3.5  1234850075
11451      68    34048     2.5  1230497715

영화3) Confessions of a Dangerous Mind

movies 데이터 처리

In [ ]:
movie_titile = "Confessions of a Dangerous Mind (2002)"
movies_df[movies_df['title'] == movie_titile]

,movie_id,title,genres
4169,6003,Confessions of a Dangerous Mind (2002),Comedy|Crime|Drama|Thriller
9106,144606,Confessions of a Dangerous Mind (2002),Comedy|Crime|Drama|Romance|Thriller

In [ ]:
unique_id = movies_df[movies_df['title'] == movie_titile]['movie_id'].values[0]
duplicated_id = movies_df[movies_df['title'] == movie_titile]['movie_id'].values[1]

In [ ]:
# 중복 데이터 제거
movies_df = movies_df[~(movies_df['movie_id'] == duplicated_id)].copy()
movies_df

,movie_id,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

ratings 데이터 처리

In [ ]:
ratings_df[ratings_df['movie_id'] == duplicated_id]

      user_id movie_id  rating   timestamp
17819     111   144606     4.0  1517441257

In [ ]:
duplicated_index = ratings_df[ratings_df['movie_id'] == duplicated_id].index
duplicated_index

Index([17819], dtype='int64')

In [ ]:
ratings_df.loc[duplicated_index, 'movie_id'] = unique_id

In [ ]:
# 검산: 삭제 여부 확인
ratings_df[ratings_df['movie_id'] == duplicated_id]

Empty DataFrame
Columns: [user_id, movie_id, rating, timestamp]
Index: []

In [ ]:
# 검산: 중복 id 변경 확인
ratings_df.loc[duplicated_index]

      user_id movie_id  rating   timestamp
17819     111     6003     4.0  1517441257

영화4) Eros

movies 데이터 처리

In [ ]:
movie_titile = "Eros (2004)"
movies_df[movies_df['title'] == movie_titile]

     movie_id        title         genres
5854    32600  Eros (2004)          Drama
9135   147002  Eros (2004)  Drama|Romance

In [ ]:
unique_id = movies_df[movies_df['title'] == movie_titile]['movie_id'].values[0]
duplicated_id = movies_df[movies_df['title'] == movie_titile]['movie_id'].values[1]

In [ ]:
# 중복 데이터 제거
movies_df = movies_df[~(movies_df['movie_id'] == duplicated_id)].copy()
movies_df

,movie_id,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

ratings 데이터 처리

In [ ]:
ratings_df[ratings_df['movie_id'] == duplicated_id]

      user_id movie_id  rating   timestamp
49832     318   147002     4.0  1502207152

In [ ]:
duplicated_index = ratings_df[ratings_df['movie_id'] == duplicated_id].index
duplicated_index

Index([49832], dtype='int64')

In [ ]:
ratings_df.loc[duplicated_index, 'movie_id'] = unique_id

In [ ]:
# 검산: 삭제 여부 확인
ratings_df[ratings_df['movie_id'] == duplicated_id]

Empty DataFrame
Columns: [user_id, movie_id, rating, timestamp]
Index: []

In [ ]:
# 검산: 중복 id 변경 확인
ratings_df.loc[duplicated_index]

      user_id movie_id  rating   timestamp
49832     318    32600     4.0  1502207152

영화5) Saturn 3

movie 데이터 처리

In [ ]:
movie_titile = "Saturn 3 (1980)"
movies_df[movies_df['title'] == movie_titile]

     movie_id            title                     genres
2141     2851  Saturn 3 (1980)  Adventure|Sci-Fi|Thriller
9468   168358  Saturn 3 (1980)            Sci-Fi|Thriller

In [ ]:
unique_id = movies_df[movies_df['title'] == movie_titile]['movie_id'].values[0]
duplicated_id = movies_df[movies_df['title'] == movie_titile]['movie_id'].values[1]

In [ ]:
# 중복 데이터 제거
movies_df = movies_df[~(movies_df['movie_id'] == duplicated_id)].copy()
movies_df

,movie_id,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

ratings 데이터 처리

In [ ]:
ratings_df[ratings_df['movie_id'] == duplicated_id]

      user_id movie_id  rating   timestamp
81458     514   168358     2.5  1533945970

In [ ]:
duplicated_index = ratings_df[ratings_df['movie_id'] == duplicated_id].index
duplicated_index

Index([81458], dtype='int64')

In [ ]:
ratings_df.loc[duplicated_index, 'movie_id'] = unique_id

In [ ]:
# 검산: 삭제 여부 확인
ratings_df[ratings_df['movie_id'] == duplicated_id]

Empty DataFrame
Columns: [user_id, movie_id, rating, timestamp]
Index: []

In [ ]:
# 검산: 중복 id 변경 확인
ratings_df.loc[duplicated_index]

      user_id movie_id  rating   timestamp
81458     514     2851     2.5  1533945970

### 중복값 처리 확인

In [ ]:
len(movies_df)

9737

In [ ]:
movies_df['movie_id'].nunique()

9737

In [ ]:
movies_df['title'].nunique()

9737

## 장르 결측치 처리

Imputation

In [ ]:
no_genre_cond = movies_df['genres'].str.contains(' ')
movies_df[no_genre_cond]

,movie_id,title,genres
8517,114335,La cravate (1957),(no genres listed)
8684,122888,Ben-hur (2016),(no genres listed)
8687,122896,Pirates of the Caribbean: Dead Men Tell No Tal...,(no genres listed)
8782,129250,Superfast! (2015),(no genres listed)
8836,132084,Let It Be Me (1995),(no genres listed)
8902,134861,Trevor Noah: African American (2013),(no genres listed)
9033,141131,Guardians (2016),(no genres listed)
9053,141866,Green Room (2015),(no genres listed)
9070,142456,The Brand New Testament (2015),(no genres listed)
9091,143410,Hyena Road,(no genres listed)
9138,147250,The Adventures of Sherlock Holmes and Doctor W...,(no genres listed)
9178,149330,A Cosmic Christmas (1977),(no genres listed)
9217,152037,Grease Live (2016),(no genres listed)
9248,155589,Noin 7 veljestä (1968),(no genres listed)
9259,156605,Paterson,(no genres listed)
9307,159161,Ali Wong: Baby Cobra (2016),(no genres listed)
9316,159779,A Midsummer Night's Dream (2016),(no genres listed)
9348,161008,The Forbidden Dance (1990),(no genres listed)
9413,165489,Ethel & Ernest (2016),(no genres listed)
9426,166024,Whiplash (2013),(no genres listed)
9448,167570,The OA,(no genres listed)
9478,169034,Lemonade (2016),(no genres listed)
9514,171495,Cosmos,(no genres listed)
9515,171631,Maria Bamford: Old Baby,(no genres listed)
9518,171749,Death Note: Desu nôto (2006–2007),(no genres listed)
9525,171891,Generation Iron 2,(no genres listed)
9534,172497,T2 3-D: Battle Across Time (1996),(no genres listed)
9541,172591,The Godfather Trilogy: 1972-1990 (1992),(no genres listed)
9562,173535,The Adventures of Sherlock Holmes and Doctor W...,(no genres listed)
9573,174403,The Putin Interviews (2017),(no genres listed)
9611,176601,Black Mirror,(no genres listed)
9661,181413,Too Funny to Fail: The Life and Death of The D...,(no genres listed)
9663,181719,Serving in Silence: The Margarethe Cammermeyer...,(no genres listed)
9669,182727,A Christmas Story Live! (2017),(no genres listed)

In [ ]:
len(movies_df[no_genre_cond])

34

In [ ]:
len(movies_df[~no_genre_cond])

9703

In [ ]:
# 장르 없으면 사용안할 것
del_movie_ids = movies_df.loc[no_genre_cond, 'movie_id'].tolist()
len(del_movie_ids)

34

In [ ]:
movies_df = movies_df[~movies_df['movie_id'].isin(del_movie_ids)].copy()
movies_df

,movie_id,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [ ]:
# 검산: 삭제 id 데이터는 없어야 한
movies_df[no_genre_cond]

/tmp/ipython-input-1277428978.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  movies_df[no_genre_cond]

Empty DataFrame
Columns: [movie_id, title, genres]
Index: []

ratings 데이터도 처리 필요

In [ ]:
len(ratings_df)

100836

In [ ]:
# 삭제할 영화 관련 데이터
len(ratings_df[ratings_df['movie_id'].isin(del_movie_ids)])

47

In [ ]:
100836 - 47  # 삭제 후 데이터 개수

100789

In [ ]:
ratings_df = ratings_df[~ratings_df['movie_id'].isin(del_movie_ids)].copy()
ratings_df

       user_id movie_id  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100789 rows x 4 columns]

## 그외 결측치 체크

In [ ]:
movies_df.columns[movies_df.isna().any()].tolist()

[]

## 인덱스 정리

In [ ]:
# 중복 제거 작업으로 인덱스 불일치 상태
movies_df

,movie_id,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [ ]:
movies_df = movies_df.reset_index(drop=True)
movies_df

,movie_id,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9698,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9699,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9700,193585,Flint (2017),Drama
9701,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9702,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [ ]:
# 중복 제거 작업으로 인덱스 불일치 상태
ratings_df

       user_id movie_id  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100789 rows x 4 columns]

In [ ]:
ratings_df = ratings_df.reset_index(drop=True)
ratings_df

       user_id movie_id  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100784     610   166534     4.0  1493848402
100785     610   168248     5.0  1493850091
100786     610   168250     5.0  1494273047
100787     610   168252     5.0  1493846352
100788     610   170875     3.0  1493846415

[100789 rows x 4 columns]

## 구분자 변경

TfidfVectorizer 사용하려면 space 를 seperator 로 써야

In [ ]:
# 장르 이름에는 빈칸 없다
# 만약 빈칸 있으면 _ 붙이는 처리 필요
# 예) k drama|fun --> k drama fun  (X)
#                 --> k_drama fun  (O)
movies_df[movies_df['genres'].str.contains(' ')]

Empty DataFrame
Columns: [movie_id, title, genres]
Index: []

In [ ]:
movies_df['genres']

0       Adventure|Animation|Children|Comedy|Fantasy
1                        Adventure|Children|Fantasy
2                                    Comedy|Romance
3                              Comedy|Drama|Romance
4                                            Comedy
                           ...
9698                Action|Animation|Comedy|Fantasy
9699                       Animation|Comedy|Fantasy
9700                                          Drama
9701                               Action|Animation
9702                                         Comedy
Name: genres, Length: 9703, dtype: object

In [ ]:
movies_df['genres'].str.replace('\|',' ', regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:1: SyntaxWarning: invalid escape sequence '\|'
/tmp/ipython-input-1891247049.py:1: SyntaxWarning: invalid escape sequence '\|'
  movies_df['genres'].str.replace('\|',' ', regex=True)

0       Adventure Animation Children Comedy Fantasy
1                        Adventure Children Fantasy
2                                    Comedy Romance
3                              Comedy Drama Romance
4                                            Comedy
                           ...
9698                Action Animation Comedy Fantasy
9699                       Animation Comedy Fantasy
9700                                          Drama
9701                               Action Animation
9702                                         Comedy
Name: genres, Length: 9703, dtype: object

In [ ]:
movies_df['genres'] = movies_df['genres'].str.replace(r'\|',' ', regex=True)
movies_df

,movie_id,title,genres
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy
1,2,Jumanji (1995),Adventure Children Fantasy
2,3,Grumpier Old Men (1995),Comedy Romance
3,4,Waiting to Exhale (1995),Comedy Drama Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9698,193581,Black Butler: Book of the Atlantic (2017),Action Animation Comedy Fantasy
9699,193583,No Game No Life: Zero (2017),Animation Comedy Fantasy
9700,193585,Flint (2017),Drama
9701,193587,Bungo Stray Dogs: Dead Apple (2018),Action Animation
9702,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

## 연도 결측치 처리

In [ ]:
# 제목에 연도 없는 데이터 검색
# movies_df[~movies_df['title'].str.contains('(')]  <-- \( 사용해야함
movies_df[~movies_df['title'].str.contains(r'\(')]

     movie_id              title                  genres
6058    40697          Babylon 5                  Sci-Fi
9023   140956   Ready Player One  Action Sci-Fi Thriller
9163   149334  Nocturnal Animals          Drama Thriller
9345   162414          Moonlight                   Drama

웹 검색으로 영화 연도 찾은 결과
```
'Babylon 5': 1994
'Ready Player One': 2018
'Nocturnal Animals': 2017
'Moonlight': 2009
```

In [ ]:
tmp = movies_df.copy()

In [ ]:
tmp.loc[6058, 'title'] = tmp.loc[6058, 'title'] + " (1994)"
tmp.loc[[6058]]

     movie_id             title  genres
6058    40697  Babylon 5 (1994)  Sci-Fi

In [ ]:
# 중복 실행 시 연도 중첩 방지 필요
tmp.loc[6058, 'title'] = tmp.loc[6058, 'title'] + " (1994)"
tmp.loc[[6058]]

     movie_id                    title  genres
6058    40697  Babylon 5 (1994) (1994)  Sci-Fi

In [ ]:
# 연도 없는지 체크
'(' not in tmp.loc[6058, 'title']

False

In [ ]:
tmp = movies_df.copy()
idx = 6058
year = 1994

if '(' not in tmp.loc[idx, 'title']:
    tmp.loc[idx, 'title'] = tmp.loc[idx, 'title'] + f" ({year})"

tmp.loc[[idx]]

     movie_id             title  genres
6058    40697  Babylon 5 (1994)  Sci-Fi

In [ ]:
# 직접 입력
idx = 6058
year = 1994
if '(' not in movies_df.loc[idx, 'title']:
    movies_df.loc[idx, 'title'] = movies_df.loc[idx, 'title'] + f" ({year})"
movies_df.loc[[idx]]

     movie_id             title  genres
6058    40697  Babylon 5 (1994)  Sci-Fi

In [ ]:
# 직접 입력
idx = 9023
year = 2018
if '(' not in movies_df.loc[idx, 'title']:
    movies_df.loc[idx, 'title'] = movies_df.loc[idx, 'title'] + f" ({year})"
movies_df.loc[[idx]]

     movie_id                    title                  genres
9023   140956  Ready Player One (2018)  Action Sci-Fi Thriller

In [ ]:
# 직접 입력
idx = 9163
year = 2017
if '(' not in movies_df.loc[idx, 'title']:
    movies_df.loc[idx, 'title'] = movies_df.loc[idx, 'title'] + f" ({year})"
movies_df.loc[[idx]]

     movie_id                     title          genres
9163   149334  Nocturnal Animals (2017)  Drama Thriller

In [ ]:
# 직접 입력
idx = 9345
year = 2009
if '(' not in movies_df.loc[idx, 'title']:
    movies_df.loc[idx, 'title'] = movies_df.loc[idx, 'title'] + f" ({year})"
movies_df.loc[[idx]]

     movie_id             title genres
9345   162414  Moonlight (2009)  Drama

In [ ]:
# 검산: 제목에 연도 없는 데이터 검색
movies_df[~movies_df['title'].str.contains(r'\(')]

Empty DataFrame
Columns: [movie_id, title, genres]
Index: []

## 영화명/연도 분리

### 연습

In [ ]:
"Waiting to Exhale (1995)".rsplit(' ', 1)

['Waiting to Exhale', '(1995)']

In [ ]:
# 여백 주의! split에 영향줌
"Waiting to Exhale (1995) ".rsplit(' ', 1)

['Waiting to Exhale (1995)', '']

In [ ]:
"Waiting to Exhale (1995) ".strip()

'Waiting to Exhale (1995)'

In [ ]:
"Waiting to Exhale (1995) ".strip().rsplit(' ', 1)

['Waiting to Exhale', '(1995)']

In [ ]:
movies_df['title'].str.rsplit(' ', n=1)

0                                [Toy Story, (1995)]
1                                  [Jumanji, (1995)]
2                         [Grumpier Old Men, (1995)]
3                        [Waiting to Exhale, (1995)]
4              [Father of the Bride Part II, (1995)]
                            ...
9698    [Black Butler: Book of the Atlantic, (2017)]
9699                 [No Game No Life: Zero, (2017)]
9700                                 [Flint, (2017)]
9701          [Bungo Stray Dogs: Dead Apple, (2018)]
9702          [Andrew Dice Clay: Dice Rules, (1991)]
Name: title, Length: 9703, dtype: object

In [ ]:
movies_df['title'].str.rsplit(' ', n=1, expand=True)

                                       0       1
0                              Toy Story  (1995)
1                                Jumanji  (1995)
2                       Grumpier Old Men  (1995)
3                      Waiting to Exhale  (1995)
4            Father of the Bride Part II  (1995)
...                                  ...     ...
9698  Black Butler: Book of the Atlantic  (2017)
9699               No Game No Life: Zero  (2017)
9700                               Flint  (2017)
9701        Bungo Stray Dogs: Dead Apple  (2018)
9702        Andrew Dice Clay: Dice Rules  (1991)

[9703 rows x 2 columns]

### 적용

In [ ]:
movies_df['title'] = movies_df['title'].str.strip()
movies_df

,movie_id,title,genres
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy
1,2,Jumanji (1995),Adventure Children Fantasy
2,3,Grumpier Old Men (1995),Comedy Romance
3,4,Waiting to Exhale (1995),Comedy Drama Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9698,193581,Black Butler: Book of the Atlantic (2017),Action Animation Comedy Fantasy
9699,193583,No Game No Life: Zero (2017),Animation Comedy Fantasy
9700,193585,Flint (2017),Drama
9701,193587,Bungo Stray Dogs: Dead Apple (2018),Action Animation
9702,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [ ]:
movies_df[['title_only', 'year']] = movies_df['title'].str.rsplit(' ', n=1, expand=True)
movies_df

,movie_id,title,genres,title_only,year
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,Toy Story,(1995)
1,2,Jumanji (1995),Adventure Children Fantasy,Jumanji,(1995)
2,3,Grumpier Old Men (1995),Comedy Romance,Grumpier Old Men,(1995)
3,4,Waiting to Exhale (1995),Comedy Drama Romance,Waiting to Exhale,(1995)
4,5,Father of the Bride Part II (1995),Comedy,Father of the Bride Part II,(1995)
...,...,...,...,...,...
9698,193581,Black Butler: Book of the Atlantic (2017),Action Animation Comedy Fantasy,Black Butler: Book of the Atlantic,(2017)
9699,193583,No Game No Life: Zero (2017),Animation Comedy Fantasy,No Game No Life: Zero,(2017)
9700,193585,Flint (2017),Drama,Flint,(2017)
9701,193587,Bungo Stray Dogs: Dead Apple (2018),Action Animation,Bungo Stray Dogs: Dead Apple,(2018)
9702,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,Andrew Dice Clay: Dice Rules,(1991)

In [ ]:
# 연도에 괄호 제거하고 int 타입 변환
movies_df['year'] = movies_df['year'].apply(lambda x: x[1:-1])
movies_df['year'] = movies_df['year'].astype(int)
movies_df

,movie_id,title,genres,title_only,year
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,Toy Story,1995
1,2,Jumanji (1995),Adventure Children Fantasy,Jumanji,1995
2,3,Grumpier Old Men (1995),Comedy Romance,Grumpier Old Men,1995
3,4,Waiting to Exhale (1995),Comedy Drama Romance,Waiting to Exhale,1995
4,5,Father of the Bride Part II (1995),Comedy,Father of the Bride Part II,1995
...,...,...,...,...,...
9698,193581,Black Butler: Book of the Atlantic (2017),Action Animation Comedy Fantasy,Black Butler: Book of the Atlantic,2017
9699,193583,No Game No Life: Zero (2017),Animation Comedy Fantasy,No Game No Life: Zero,2017
9700,193585,Flint (2017),Drama,Flint,2017
9701,193587,Bungo Stray Dogs: Dead Apple (2018),Action Animation,Bungo Stray Dogs: Dead Apple,2018
9702,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,Andrew Dice Clay: Dice Rules,1991

In [ ]:
# 영화명 같이만 개봉 연도 다른 리메이크작 존재함
# title_only 보다 title 그대로 사용
movies_df = movies_df[['movie_id', 'title', 'year', 'genres']]
movies_df

,movie_id,title,year,genres
0,1,Toy Story (1995),1995,Adventure Animation Children Comedy Fantasy
1,2,Jumanji (1995),1995,Adventure Children Fantasy
2,3,Grumpier Old Men (1995),1995,Comedy Romance
3,4,Waiting to Exhale (1995),1995,Comedy Drama Romance
4,5,Father of the Bride Part II (1995),1995,Comedy
...,...,...,...,...
9698,193581,Black Butler: Book of the Atlantic (2017),2017,Action Animation Comedy Fantasy
9699,193583,No Game No Life: Zero (2017),2017,Animation Comedy Fantasy
9700,193585,Flint (2017),2017,Drama
9701,193587,Bungo Stray Dogs: Dead Apple (2018),2018,Action Animation
9702,193609,Andrew Dice Clay: Dice Rules (1991),1991,Comedy

# 데이터 저장

In [ ]:
movie_file_path = DATA_DIR / "movies_refined.csv"
movie_file_path

PosixPath('drive/MyDrive/kw/추천특강/강의자료/data/movies_refined.csv')

In [ ]:
movies_df.to_csv(movie_file_path, index=False)
movies_df

,movie_id,title,year,genres
0,1,Toy Story (1995),1995,Adventure Animation Children Comedy Fantasy
1,2,Jumanji (1995),1995,Adventure Children Fantasy
2,3,Grumpier Old Men (1995),1995,Comedy Romance
3,4,Waiting to Exhale (1995),1995,Comedy Drama Romance
4,5,Father of the Bride Part II (1995),1995,Comedy
...,...,...,...,...
9698,193581,Black Butler: Book of the Atlantic (2017),2017,Action Animation Comedy Fantasy
9699,193583,No Game No Life: Zero (2017),2017,Animation Comedy Fantasy
9700,193585,Flint (2017),2017,Drama
9701,193587,Bungo Stray Dogs: Dead Apple (2018),2018,Action Animation
9702,193609,Andrew Dice Clay: Dice Rules (1991),1991,Comedy

In [ ]:
ratings_file_path = DATA_DIR / "ratings_refined.csv"
ratings_file_path

PosixPath('drive/MyDrive/kw/추천특강/강의자료/data/ratings_refined.csv')

In [ ]:
ratings_df.to_csv(ratings_file_path, index=False)
ratings_df

       user_id movie_id  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100784     610   166534     4.0  1493848402
100785     610   168248     5.0  1493850091
100786     610   168250     5.0  1494273047
100787     610   168252     5.0  1493846352
100788     610   170875     3.0  1493846415

[100789 rows x 4 columns]

# 참고

Timstamp -> Datetime

In [ ]:
from datetime import datetime
datetime.fromtimestamp(964982703)

datetime.datetime(2000, 7, 30, 18, 45, 3)

In [ ]:
time_unit = 2
datetime.fromtimestamp(964982703 / time_unit)

datetime.datetime(1985, 4, 16, 9, 22, 31, 500000)

In [ ]:
from datetime import datetime
tmp = ratings_df.copy()
time_unit = 2
tmp['datetime'] = tmp['timestamp'].apply(lambda x: datetime.fromtimestamp(x/time_unit))
tmp

       user_id movie_id  rating   timestamp                datetime
0            1        1     4.0   964982703 1985-04-16 09:22:31.500
1            1        3     4.0   964981247 1985-04-16 09:10:23.500
2            1        6     4.0   964982224 1985-04-16 09:18:32.000
3            1       47     5.0   964983815 1985-04-16 09:31:47.500
4            1       50     5.0   964982931 1985-04-16 09:24:25.500
...        ...      ...     ...         ...                     ...
100784     610   166534     4.0  1493848402 1993-09-01 22:56:41.000
100785     610   168248     5.0  1493850091 1993-09-01 23:10:45.500
100786     610   168250     5.0  1494273047 1993-09-04 09:55:23.500
100787     610   168252     5.0  1493846352 1993-09-01 22:39:36.000
100788     610   170875     3.0  1493846415 1993-09-01 22:40:07.500

[100789 rows x 5 columns]